import Head from "next/head";
import WelcomePage from "./welcome";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to Next.JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WelcomePage /> {/*Here I imported my welcome page component into my main index page, but the welcome page is also on it's own route*/}
      </main>
    </>
  );
}
